apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment-processor
  namespace: payment-system
spec:
  replicas: 3
  selector:
    matchLabels:
      app: payment-processor
  template:
    metadata:
      labels:
        app: payment-processor
    spec:
      containers:
      - name: payment-processor
        image: payment-processor:latest
        env:
        - name: POSTGRES_HOST
          value: postgres
        - name: POSTGRES_DB
          value: transactions
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: db-credentials
              key: username
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: db-credentials
              key: password
        - name: KAFKA_BOOTSTRAP_SERVERS
          value: kafka:29092
        resources:
          requests:
            memory: "256Mi"
            cpu: "200m"
          limits:
            memory: "512Mi"
            cpu: "500m" 